spring.application.name=mongodbrecommendationsystem

spring.data.mongodb.uri = mongodb://localhost:27017/thesis_dataset
//spring.data.mongodb.uri = mongodb://localhost:27017/test
server.port = 8080

server.servlet.context-path=/recommendation-system