spring.application.name=mongodbrecommendationsystem

spring.data.mongodb.uri = mongodb://localhost:27017/test
#spring.data.mongodb.uri = mongodb+srv://taskmanager:taskmanager@cluster0.s08jtsg.mongodb.net/stock_management
server.port = 8080

server.servlet.context-path=/recommendation-system
